### ISSUE TITLE
No module named 'diffusers.pipelines.onnx_utils'

### ISSUE THREAD

**Issue by CHMimilanlan** [Tencent/Frankenstein#1]
When I ran code `python test_diff.py -e diff_denoising/configs/diff_bedroom/ -u painting_bedroom/62d0964d-a9c3-4f54-a1d5-4709a289193f_MasterBedroom-11117/`
I get following error, could you please tell me how to solve this? 

Loading pipeline components...:   0%|                                                      | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/utils/import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/data/xch/tools/anaconda/envs/chm/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'diffusers.pipelines.onnx_utils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/xch/Avatar/3D/Frankenstein/test_diff.py", line 89, in <module>
    test(args)
  File "/data/xch/Avatar/3D/Frankenstein/test_diff.py", line 17, in test
    generator = DDPMPipelineTriplane.from_pretrained(args.exp_dir, use_safetensors=True).to("cuda")
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/pipelines/pipeline_utils.py", line 1206, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/pipelines/pipeline_utils.py", line 389, in load_sub_model
    class_obj, class_candidates = get_class_obj_and_candidates(
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/pipelines/pipeline_utils.py", line 320, in get_class_obj_and_candidates
    class_candidates = {c: getattr(library, c, None) for c in importable_classes.keys()}
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/pipelines/pipeline_utils.py", line 320, in <dictcomp>
    class_candidates = {c: getattr(library, c, None) for c in importable_classes.keys()}
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/utils/import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/utils/import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/xch/Avatar/3D/Frankenstein/diffusers/utils/import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.onnx_utils because of the following error (look up to see its traceback):
No module named 'diffusers.pipelines.onnx_utils'

I will be grateful for your timely response!

**Comment by CHMimilanlan** [comment]
Never mind, I have solved this problem by directly download file onnx_utils.py and put it to corresponding directory. 
For the sake of convenience, my download link is here https://www.aicgworld.com/pb/diffusers/-/blob/325a5de3a9acc97534a4446ce9dd4147efcd61a0/src/diffusers/pipelines/onnx_utils.py

**Comment by wolfball** [comment]
> https://www.aicgworld.com/pb/diffusers/-/blob/325a5de3a9acc97534a4446ce9dd4147efcd61a0/src/diffusers/pipelines/onnx_utils.py

Sorry for the inconvenience; I did not encounter this problem during testing. Also, thank you for providing the link.
